<?php

use Symfony\Component\HttpFoundation\RedirectResponse;

function form_example_cancelar(){

 global $base_url;
 //dpm($base_url);

 drupal_set_message(t('Acción Cancelada!'), 'error');

 $respuesta = new RedirectResponse($base_url . '/form_example', 302);
 $respuesta->send();
 return;

}

function form_example_theme($existing, $type, $theme, $path) {
  return [
    'form_example_template' => [
      'variables' => ['registro_id' => NULL],
    ],
  ];
}


?>
